config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => "user_registrations" }
	resources :users
	resources :orders, only: [:index, :show, :create, :destroy]
	resources :products do
		resources :comments
	end
	get 'static_pages/about'

	get 'static_pages/contact'

	root 'static_pages#landing_page'

	post 'static_pages/thank_you'

  get 'payments/create'

  post 'payments/create'

  mount ActionCable.server => '/cable'

end
# devise_for :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer:true }
  after_create_commit { CommentUpdateJob.perform_later(self, @user) }
  belongs_to :user
  belongs_to :product

  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(:rating)}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product=Product.find(params[:product_id])
    @comment=@product.comments.new(comment_params)
    @comment.user= current_user
    @user = current_user
    respond_to do |format|
      if @comment.save
        # ActionCable.server.broadcast 'product_channel', comment: @comment
        format.html { redirect_to @product, notice: 'Review was created sucessfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end



  private
  def	comment_params
      params.require(:comment).permit(:user_id, :body, :rating)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <% if current_user && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <%= comment.user.first_name %>
    <small><em>
      <%= "#{time_ago_in_words(comment.created_at)} ago" %>
    </em></small>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p>
    <%= comment.body %>
  </p>
</div>

app/views/comments/create.js.erb
$('#new_comment').html("Thank you! Your review is appreciated!");

// $('.product-reviews').prepend("<%= j render @comment %>");

$("#average-rating").attr('data-score', "<%= @product.average_rating %>");

$(document).on('turbolinks:load ajaxSuccess', function() {
  refreshRating();
});