config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => "user_registrations" }
	resources :users
	resources :orders, only: [:index, :show, :create, :destroy]
	resources :products do
		resources :comments
	end
	get 'static_pages/about'

	get 'static_pages/contact'

	root 'static_pages#landing_page'

	post 'static_pages/thank_you'

  get 'payments/create'

  post 'payments/create'

  mount ActionCable.server => '/cable'

end
# devise_for :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Firstapp</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
           data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
           <div class="search">
            <%= form_tag("/products", method: "get") do %>
             <%= text_field_tag (:q) %>
             <%= submit_tag("SEARCH" , :class => "submit-button") %>
            <% end %>
          </div>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right" id="navbar">
            <li>
              <%= link_to 'HOME', root_path %>
            </li>
            <li>
              <%= link_to 'BIKES', products_url %>
            </li>
            <li>
              <%= link_to 'ABOUT', static_pages_about_path %>
            </li>
            <li>
              <%= link_to 'CONTACT', static_pages_contact_path %>
            </li>
            <li id="login">
              <% if current_user %>
                <%= link_to('LOGOUT', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
  	</nav>
    <% if notice %>
      <p id="notice" class="alert alert-info"> <%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-warning"> <%= alert %></p>
    <% end %>

    <%= yield %>

    <hr class="divider">
    <footer>
    &copy; 2016 Austin Bikes
    </footer>
  </body>
</html>